image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm ci
          - npm run build
          - npm test

pipelines:
  pull-requests:
    '**':
      - step: *build-test
  
  branches:
    main:
      - step: *build-test
      - step:
          name: Deploy to Dev
          deployment: dev
          oidc: true
          script:
            # Install AWS CLI
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - unzip awscliv2.zip
            - ./aws/install
            # Set up AWS OIDC authentication
            - export AWS_REGION=us-east-1
            - export AWS_ROLE_ARN=$AWS_ROLE_ARN
            - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
            - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
            # Verify AWS credentials and get temporary credentials
            - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
              $(aws sts assume-role-with-web-identity \
              --role-arn $AWS_ROLE_ARN \
              --role-session-name "BitbucketPipelineSession" \
              --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text))
            # Verify credentials again after assume-role
            - aws sts get-caller-identity
            # Install dependencies and deploy
            - npm run cdk deploy "hvt-dev-cicd-stack" -- --require-approval never 