image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - npm ci
          - npm run build
          - npm test

pipelines:
  pull-requests:
    '**':
      - step: *build-test
  
  branches:
    main:
      - step: *build-test
      - step:
          name: Deploy to Dev
          deployment: dev
          script:
            - pipe: atlassian/aws-oidc-assume-role:1.0.0
              variables:
                ROLE_ARN: $AWS_ROLE_ARN
                AWS_DEFAULT_REGION: 'us-east-1'
            - npm ci
            - npm run build
            - npm run cdk deploy "hvt-dev-cicd-stack" -- --require-approval never 