image: amazon/aws-cli

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        image: node:18
        caches:
          - node
        script:
          - npm ci
          - npm run build
          - npm test

pipelines:
  pull-requests:
    '**':
      - step: *build-test
  
  branches:
    main:
      - step: *build-test
      - step:
          name: Deploy to Dev
          deployment: dev
          oidc: true
          script:
            # Set up AWS OIDC authentication
            - export AWS_REGION=us-east-1
            - export AWS_ROLE_ARN=$AWS_ROLE_ARN
            - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
            - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
            # Install Node and npm for CDK
            - yum install -y nodejs npm
            # Install dependencies and deploy
            - npm ci
            - npm run build
            # Use AWS CLI to run CDK directly
            - npx cdk deploy "hvt-dev-cicd-stack" --require-approval never 